branch-defaults:
  Web:
    environment: dev-env
global:
  application_name: NonStopParty
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2015.09 v2.0.8 running Node.js
  default_region: us-west-2
  profile: eb-cli
  sc: git
