# Uncomment this line to define a global platform for your project
 platform :ios, '9.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'NonStopParty' do
	pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift2'	
	pod 'Alamofire'
	pod 'FBSDKCoreKit'
	pod 'FBSDKLoginKit'
	pod 'FBSDKShareKit'
	pod 'BubbleTransition', '~> 1.0.0'

end



